# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alerts.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='alerts.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x61lerts.proto\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\r\x12\t\n\x01y\x18\x02 \x01(\r\"k\n\x08ObjectId\x12\x1d\n\tobject_id\x18\x01 \x01(\x0e\x32\n.OBJECT_ID\x12\x12\n\nconfidence\x18\x02 \x01(\r\x12\x16\n\x0emajority_count\x18\x03 \x01(\r\x12\x14\n\x0cmajority_min\x18\x04 \x01(\r\"L\n\x07Warning\x12\n\n\x02id\x18\x01 \x01(\r\x12\x16\n\x06points\x18\x02 \x03(\x0b\x32\x06.Point\x12\x1d\n\nobject_ids\x18\x03 \x03(\x0b\x32\t.ObjectId\"\x1c\n\x08Warnings\x12\x10\n\x08warnings\x18\x01 \x01(\r*J\n\tOBJECT_ID\x12\n\n\x06PERSON\x10\x00\x12\x07\n\x03\x44OG\x10\x01\x12\x07\n\x03\x43\x41T\x10\x02\x12\t\n\x05\x43HAIR\x10\x03\x12\x07\n\x03\x43\x41R\x10\x04\x12\x0b\n\x07\x42ICYCLE\x10\x05*J\n\x06OPCODE\x12\n\n\x06HEADER\x10\x00\x12\x07\n\x03\x41\x43K\x10\x01\x12\x08\n\x04NACK\x10\x02\x12\x13\n\x0fPOLYGON_SETTING\x10\x03\x12\x0c\n\x08WARNINGS\x10\x04\x62\x06proto3')
)

_OBJECT_ID = _descriptor.EnumDescriptor(
  name='OBJECT_ID',
  full_name='OBJECT_ID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PERSON', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOG', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHAIR', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAR', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BICYCLE', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=264,
  serialized_end=338,
)
_sym_db.RegisterEnumDescriptor(_OBJECT_ID)

OBJECT_ID = enum_type_wrapper.EnumTypeWrapper(_OBJECT_ID)
_OPCODE = _descriptor.EnumDescriptor(
  name='OPCODE',
  full_name='OPCODE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HEADER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NACK', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POLYGON_SETTING', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARNINGS', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=340,
  serialized_end=414,
)
_sym_db.RegisterEnumDescriptor(_OPCODE)

OPCODE = enum_type_wrapper.EnumTypeWrapper(_OPCODE)
PERSON = 0
DOG = 1
CAT = 2
CHAIR = 3
CAR = 4
BICYCLE = 5
HEADER = 0
ACK = 1
NACK = 2
POLYGON_SETTING = 3
WARNINGS = 4



_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Point.x', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Point.y', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=45,
)


_OBJECTID = _descriptor.Descriptor(
  name='ObjectId',
  full_name='ObjectId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_id', full_name='ObjectId.object_id', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='ObjectId.confidence', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='majority_count', full_name='ObjectId.majority_count', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='majority_min', full_name='ObjectId.majority_min', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=154,
)


_WARNING = _descriptor.Descriptor(
  name='Warning',
  full_name='Warning',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Warning.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points', full_name='Warning.points', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object_ids', full_name='Warning.object_ids', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=232,
)


_WARNINGS = _descriptor.Descriptor(
  name='Warnings',
  full_name='Warnings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='warnings', full_name='Warnings.warnings', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=262,
)

_OBJECTID.fields_by_name['object_id'].enum_type = _OBJECT_ID
_WARNING.fields_by_name['points'].message_type = _POINT
_WARNING.fields_by_name['object_ids'].message_type = _OBJECTID
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['ObjectId'] = _OBJECTID
DESCRIPTOR.message_types_by_name['Warning'] = _WARNING
DESCRIPTOR.message_types_by_name['Warnings'] = _WARNINGS
DESCRIPTOR.enum_types_by_name['OBJECT_ID'] = _OBJECT_ID
DESCRIPTOR.enum_types_by_name['OPCODE'] = _OPCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'alerts_pb2'
  # @@protoc_insertion_point(class_scope:Point)
  ))
_sym_db.RegisterMessage(Point)

ObjectId = _reflection.GeneratedProtocolMessageType('ObjectId', (_message.Message,), dict(
  DESCRIPTOR = _OBJECTID,
  __module__ = 'alerts_pb2'
  # @@protoc_insertion_point(class_scope:ObjectId)
  ))
_sym_db.RegisterMessage(ObjectId)

Warning = _reflection.GeneratedProtocolMessageType('Warning', (_message.Message,), dict(
  DESCRIPTOR = _WARNING,
  __module__ = 'alerts_pb2'
  # @@protoc_insertion_point(class_scope:Warning)
  ))
_sym_db.RegisterMessage(Warning)

Warnings = _reflection.GeneratedProtocolMessageType('Warnings', (_message.Message,), dict(
  DESCRIPTOR = _WARNINGS,
  __module__ = 'alerts_pb2'
  # @@protoc_insertion_point(class_scope:Warnings)
  ))
_sym_db.RegisterMessage(Warnings)


# @@protoc_insertion_point(module_scope)
