/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Wed Jul 18 14:16:52 2018. */

#include "alerts.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Point_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Point, x, x, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, Point, y, x, 0),
    PB_LAST_FIELD
};

const pb_field_t ObjectId_fields[5] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, ObjectId, object_id, object_id, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, ObjectId, confidence, object_id, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, ObjectId, majority_count, confidence, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, ObjectId, majority_min, majority_count, 0),
    PB_LAST_FIELD
};

const pb_field_t Warning_fields[4] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Warning, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, Warning, points, id, &Point_fields),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, Warning, object_ids, points, &ObjectId_fields),
    PB_LAST_FIELD
};

const pb_field_t Warnings_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Warnings, warnings, warnings, 0),
    PB_LAST_FIELD
};




/* @@protoc_insertion_point(eof) */
