/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Sun Jul 15 09:44:05 2018. */

#include "alerts.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Header_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, Header, opcode, opcode, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, STATIC  , OTHER, Header, message_data, opcode, 0),
    PB_LAST_FIELD
};

const pb_field_t Point_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Point, x, x, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, Point, y, x, 0),
    PB_LAST_FIELD
};

const pb_field_t ObjectId_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, ObjectId, object_id, object_id, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, ObjectId, confidence, object_id, 0),
    PB_LAST_FIELD
};

const pb_field_t Polygon_fields[3] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, Polygon, points, points, &Point_fields),
    PB_FIELD(  2, MESSAGE , REPEATED, STATIC  , OTHER, Polygon, object_ids, points, &ObjectId_fields),
    PB_LAST_FIELD
};

const pb_field_t WarningSettings_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, WarningSettings, polygons, polygons, &Polygon_fields),
    PB_LAST_FIELD
};

const pb_field_t Warnings_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, STATIC  , FIRST, Warnings, wornings, wornings, 0),
    PB_LAST_FIELD
};




/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Polygon, points[0]) < 65536 && pb_membersize(Polygon, object_ids[0]) < 65536 && pb_membersize(WarningSettings, polygons[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Header_Point_ObjectId_Polygon_WarningSettings_Warnings)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Polygon, points[0]) < 256 && pb_membersize(Polygon, object_ids[0]) < 256 && pb_membersize(WarningSettings, polygons[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Header_Point_ObjectId_Polygon_WarningSettings_Warnings)
#endif


/* @@protoc_insertion_point(eof) */
