/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Wed Jul 18 10:00:33 2018. */

#include "alerts.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Point_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Point, x, x, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, Point, y, x, 0),
    PB_LAST_FIELD
};

const pb_field_t ObjectId_fields[5] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, ObjectId, object_id, object_id, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, ObjectId, confidence, object_id, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, ObjectId, majority_count, confidence, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, ObjectId, majority_min, majority_count, 0),
    PB_LAST_FIELD
};

const pb_field_t Warning_fields[4] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Warning, id, id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, STATIC  , OTHER, Warning, points, id, &Point_fields),
    PB_FIELD(  3, MESSAGE , REPEATED, STATIC  , OTHER, Warning, object_ids, points, &ObjectId_fields),
    PB_LAST_FIELD
};

const pb_field_t Warnings_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Warnings, wornings, wornings, 0),
    PB_LAST_FIELD
};




/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Warning, points[0]) < 65536 && pb_membersize(Warning, object_ids[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Point_ObjectId_Warning_Warnings)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Warning, points[0]) < 256 && pb_membersize(Warning, object_ids[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Point_ObjectId_Warning_Warnings)
#endif


/* @@protoc_insertion_point(eof) */
